version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    environment:
      - POSTGRES_HOST = 127.0.0.1
      - POSTGRES_PORT = 5432
      - POSTGRES_USER = postgres
      - POSTGRES_PASSWORD = postgres
      - POSTGRES_DATABASE = crud
    ports:
      - 3000:3000
    depends_on:
      - postgres
    links:
      - postgres:postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev

  postgres:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER = postgres
      - POSTGRES_PASSWORD = postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
